export const queryKeys = {
  auth: ['auth'] as const,
  dashboard: ['dashboard'] as const,
  helpCenter: ['help-center'] as const,
  analytics: ['analytics'] as const,
  employees: ['employees'] as const,
  employeeDetail: (id: string) => ['employees', id] as const,
  employeeAttendancePolicy: (id: string) => ['employees', id, 'attendance-policy'] as const,
  departments: ['departments'] as const,
  departmentDetail: (id: string) => ['departments', id] as const,
  departmentCatalog: ['departments', 'catalog'] as const,
  timeRecords: ['time-records'] as const,
  timeRecordCatalog: ['time-records', 'catalog'] as const,
  justifications: ['justifications'] as const,
  vacations: ['vacations'] as const,
  vacationDetail: (id: string) => ['vacations', id] as const,
  vacationEmployees: ['vacations', 'employees'] as const,
  schedules: ['schedules'] as const,
  scheduleCatalog: ['schedules', 'catalog'] as const,
  payroll: ['payroll'] as const,
  payrollDetail: (id: string) => ['payroll', id] as const,
  documents: ['documents'] as const,
  onboarding: ['onboarding'] as const,
  onboardingDetail: (id: string) => ['onboarding', id] as const,
  settings: ['settings'] as const,
  notifications: ['notifications'] as const,
  globalSearch: (term: string) => ['global-search', term] as const,
  audit: ['audit'] as const,
  auditDetail: (id: string) => ['audit', id] as const,
};
