query ListAuditLogs @auth(level: USER, insecureReason: "Operação administrativa do MVP para o painel interno de RH.") {
  auditLogs(orderBy: [{ createdAt: DESC }], limit: 300) {
    id
    user {
      id
    }
    entityName
    entityId
    action
    description
    oldData
    newData
    ipAddress
    deviceInfo
    createdAt
  }
}

mutation CreateAuditLog(
  $userId: UUID
  $entityName: String!
  $entityId: String
  $action: String!
  $description: String
  $oldData: Any
  $newData: Any
  $ipAddress: String
  $deviceInfo: String
) @auth(level: USER, insecureReason: "Operação administrativa do MVP para o painel interno de RH.") {
  auditLog_insert(
    data: {
      user: { id: $userId }
      entityName: $entityName
      entityId: $entityId
      action: $action
      description: $description
      oldData: $oldData
      newData: $newData
      ipAddress: $ipAddress
      deviceInfo: $deviceInfo
      createdAt_expr: "request.time"
    }
  )
}
