import { initializeApp, type FirebaseApp } from 'firebase/app';

import { parseFirebaseEnv, type FirebaseEnv } from '@rh-ponto/config';

let firebaseApp: FirebaseApp | null = null;

const getExplicitRuntimeFirebaseEnv = (): Partial<FirebaseEnv> => ({
  NEXT_PUBLIC_FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  NEXT_PUBLIC_FIREBASE_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  NEXT_PUBLIC_FIREBASE_DATA_CONNECT_EMULATOR_HOST: process.env.NEXT_PUBLIC_FIREBASE_DATA_CONNECT_EMULATOR_HOST,
  NEXT_PUBLIC_FIREBASE_DATA_CONNECT_EMULATOR_PORT: process.env.NEXT_PUBLIC_FIREBASE_DATA_CONNECT_EMULATOR_PORT
    ? Number(process.env.NEXT_PUBLIC_FIREBASE_DATA_CONNECT_EMULATOR_PORT)
    : undefined,
  EXPO_PUBLIC_FIREBASE_API_KEY: process.env.EXPO_PUBLIC_FIREBASE_API_KEY,
  EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN: process.env.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN,
  EXPO_PUBLIC_FIREBASE_PROJECT_ID: process.env.EXPO_PUBLIC_FIREBASE_PROJECT_ID,
  EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET: process.env.EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET,
  EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: process.env.EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  EXPO_PUBLIC_FIREBASE_APP_ID: process.env.EXPO_PUBLIC_FIREBASE_APP_ID,
  EXPO_PUBLIC_FIREBASE_DATA_CONNECT_URL: process.env.EXPO_PUBLIC_FIREBASE_DATA_CONNECT_URL,
  EXPO_PUBLIC_FIREBASE_DATA_CONNECT_EMULATOR_HOST: process.env.EXPO_PUBLIC_FIREBASE_DATA_CONNECT_EMULATOR_HOST,
  EXPO_PUBLIC_FIREBASE_DATA_CONNECT_EMULATOR_PORT: process.env.EXPO_PUBLIC_FIREBASE_DATA_CONNECT_EMULATOR_PORT
    ? Number(process.env.EXPO_PUBLIC_FIREBASE_DATA_CONNECT_EMULATOR_PORT)
    : undefined,
});

const resolveFirebaseEnv = (envInput: unknown): FirebaseEnv => {
  const inputEnv =
    envInput && typeof envInput === 'object' ? (envInput as Record<string, unknown>) : {};

  return parseFirebaseEnv({
    ...inputEnv,
    ...getExplicitRuntimeFirebaseEnv(),
  }) as FirebaseEnv;
};

export const getFirebaseApp = (envInput: unknown): FirebaseApp => {
  if (firebaseApp) {
    return firebaseApp;
  }

  const env = resolveFirebaseEnv(envInput);

  firebaseApp = initializeApp({
    apiKey: env.NEXT_PUBLIC_FIREBASE_API_KEY ?? env.EXPO_PUBLIC_FIREBASE_API_KEY,
    authDomain: env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN ?? env.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: env.NEXT_PUBLIC_FIREBASE_PROJECT_ID ?? env.EXPO_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET ?? env.EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId:
      env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID ?? env.EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: env.NEXT_PUBLIC_FIREBASE_APP_ID ?? env.EXPO_PUBLIC_FIREBASE_APP_ID,
  });

  return firebaseApp;
};
